### ISSUE TITLE
Apply `define` from vite's config

### ISSUE THREAD

**Issue by o-alexandrov** [sxyazi/vite-plugin-native-sw#2]
Thank you for a very useful plugin to have a fully custom service worker!

## Problem

Currently, if you use `define` in vite's config, it won't affect the service worker's bundle.

## Request

It would be great, if the plugin would apply `define`, if `define` exists in the config.

**Comment by sxyazi** [comment]
Hi, it's a useful feature, nice to hear about it!

After my test, it seems like `import '@vite/env'` or `import '@vite/client'` missing on development, cause there is a difference of Vite, in the mechanism to process the `define` between dev and prod.

I will try to add it, and after publishing a new version. 😃
